openapi: 3.0.0
info:
  title: Geocoding API
  version: 1.0.0
paths:
  /geocode:
    get:
      summary: Get geocode information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                type: FeatureCollection
                attribution: https://docs.traveltime.com/api/reference/geocoding-attribution
                features:
                  - type: Feature
                    geometry:
                      type: Point
                      coordinates:
                        - 9.98569
                        - 53.55243
                    properties:
                      name: Axel-Springer-Platz 2, 20355 Hamburg, Germany
                      label: Axel-Springer-Platz 2, 20355 Hamburg, Germany
                      category: building
                      type: residential
                      score: 0.74
                      house_number: "2"
                      street: Axel-Springer-Platz
                      county: Hamburg
                      macroregion: Hamburg
                      city: Hamburg
                      district: Neustadt
                      country: Germany
                      country_code: DEU
                      postcode: "20355"
                      features:
                        public_transport:
                          date_start: "2025-04-26T00:00:00+02:00"
                          date_end: "2025-06-29T00:00:00+02:00"
                        cross_country_modes: []
                        fares: false
                        postcodes: false
components:
  schemas:
    FeatureCollection:
      type: object
      properties:
        type:
          type: string
        attribution:
          type: string
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
    Feature:
      type: object
      properties:
        type:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
        properties:
          $ref: '#/components/schemas/Properties'
    Geometry:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: number
    Properties:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        category:
          type: string
        type:
          type: string
        score:
          type: number
        house_number:
          type: string
        street:
          type: string
        county:
          type: string
        macroregion:
          type: string
        city:
          type: string
        district:
          type: string
        country:
          type: string
        country_code:
          type: string
        postcode:
          type: string
        features:
          type: object
          properties:
            public_transport:
              type: object
              properties:
                date_start:
                  type: string
                  format: date-time
                date_end:
                  type: string
                  format: date-time
            cross_country_modes:
              type: array
              items: {}
            fares:
              type: boolean
            postcodes:
              type: boolean
